/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as OutrosRouteImport } from './routes/outros'
import { Route as OpiniaoRouteImport } from './routes/opiniao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LivrosRouteImport } from './routes/livros'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as CorridasRouteImport } from './routes/corridas'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OpiniaoIdRouteImport } from './routes/opiniao.$id'
import { Route as AdminFacetRouteImport } from './routes/admin.$facet'

const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const OutrosRoute = OutrosRouteImport.update({
  id: '/outros',
  path: '/outros',
  getParentRoute: () => rootRouteImport,
} as any)
const OpiniaoRoute = OpiniaoRouteImport.update({
  id: '/opiniao',
  path: '/opiniao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosRoute = LivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const CorridasRoute = CorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OpiniaoIdRoute = OpiniaoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OpiniaoRoute,
} as any)
const AdminFacetRoute = AdminFacetRouteImport.update({
  id: '/$facet',
  path: '/$facet',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artigos': typeof ArtigosRoute
  '/corridas': typeof CorridasRoute
  '/eventos': typeof EventosRoute
  '/livros': typeof LivrosRoute
  '/login': typeof LoginRoute
  '/opiniao': typeof OpiniaoRouteWithChildren
  '/outros': typeof OutrosRoute
  '/projetos': typeof ProjetosRoute
  '/viagens': typeof ViagensRoute
  '/admin/$facet': typeof AdminFacetRoute
  '/opiniao/$id': typeof OpiniaoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/corridas': typeof CorridasRoute
  '/eventos': typeof EventosRoute
  '/livros': typeof LivrosRoute
  '/login': typeof LoginRoute
  '/opiniao': typeof OpiniaoRouteWithChildren
  '/outros': typeof OutrosRoute
  '/projetos': typeof ProjetosRoute
  '/viagens': typeof ViagensRoute
  '/admin/$facet': typeof AdminFacetRoute
  '/opiniao/$id': typeof OpiniaoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artigos': typeof ArtigosRoute
  '/corridas': typeof CorridasRoute
  '/eventos': typeof EventosRoute
  '/livros': typeof LivrosRoute
  '/login': typeof LoginRoute
  '/opiniao': typeof OpiniaoRouteWithChildren
  '/outros': typeof OutrosRoute
  '/projetos': typeof ProjetosRoute
  '/viagens': typeof ViagensRoute
  '/admin/$facet': typeof AdminFacetRoute
  '/opiniao/$id': typeof OpiniaoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artigos'
    | '/corridas'
    | '/eventos'
    | '/livros'
    | '/login'
    | '/opiniao'
    | '/outros'
    | '/projetos'
    | '/viagens'
    | '/admin/$facet'
    | '/opiniao/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigos'
    | '/corridas'
    | '/eventos'
    | '/livros'
    | '/login'
    | '/opiniao'
    | '/outros'
    | '/projetos'
    | '/viagens'
    | '/admin/$facet'
    | '/opiniao/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artigos'
    | '/corridas'
    | '/eventos'
    | '/livros'
    | '/login'
    | '/opiniao'
    | '/outros'
    | '/projetos'
    | '/viagens'
    | '/admin/$facet'
    | '/opiniao/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtigosRoute: typeof ArtigosRoute
  CorridasRoute: typeof CorridasRoute
  EventosRoute: typeof EventosRoute
  LivrosRoute: typeof LivrosRoute
  LoginRoute: typeof LoginRoute
  OpiniaoRoute: typeof OpiniaoRouteWithChildren
  OutrosRoute: typeof OutrosRoute
  ProjetosRoute: typeof ProjetosRoute
  ViagensRoute: typeof ViagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outros': {
      id: '/outros'
      path: '/outros'
      fullPath: '/outros'
      preLoaderRoute: typeof OutrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opiniao': {
      id: '/opiniao'
      path: '/opiniao'
      fullPath: '/opiniao'
      preLoaderRoute: typeof OpiniaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros': {
      id: '/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof LivrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corridas': {
      id: '/corridas'
      path: '/corridas'
      fullPath: '/corridas'
      preLoaderRoute: typeof CorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/opiniao/$id': {
      id: '/opiniao/$id'
      path: '/$id'
      fullPath: '/opiniao/$id'
      preLoaderRoute: typeof OpiniaoIdRouteImport
      parentRoute: typeof OpiniaoRoute
    }
    '/admin/$facet': {
      id: '/admin/$facet'
      path: '/$facet'
      fullPath: '/admin/$facet'
      preLoaderRoute: typeof AdminFacetRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFacetRoute: typeof AdminFacetRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFacetRoute: AdminFacetRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OpiniaoRouteChildren {
  OpiniaoIdRoute: typeof OpiniaoIdRoute
}

const OpiniaoRouteChildren: OpiniaoRouteChildren = {
  OpiniaoIdRoute: OpiniaoIdRoute,
}

const OpiniaoRouteWithChildren =
  OpiniaoRoute._addFileChildren(OpiniaoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtigosRoute: ArtigosRoute,
  CorridasRoute: CorridasRoute,
  EventosRoute: EventosRoute,
  LivrosRoute: LivrosRoute,
  LoginRoute: LoginRoute,
  OpiniaoRoute: OpiniaoRouteWithChildren,
  OutrosRoute: OutrosRoute,
  ProjetosRoute: ProjetosRoute,
  ViagensRoute: ViagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
