/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as LivrosRouteImport } from './routes/livros'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as CorridasRouteImport } from './routes/corridas'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as IndexRouteImport } from './routes/index'

const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrosRoute = LivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const CorridasRoute = CorridasRouteImport.update({
  id: '/corridas',
  path: '/corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/corridas': typeof CorridasRoute
  '/eventos': typeof EventosRoute
  '/livros': typeof LivrosRoute
  '/projetos': typeof ProjetosRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/corridas': typeof CorridasRoute
  '/eventos': typeof EventosRoute
  '/livros': typeof LivrosRoute
  '/projetos': typeof ProjetosRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRoute
  '/corridas': typeof CorridasRoute
  '/eventos': typeof EventosRoute
  '/livros': typeof LivrosRoute
  '/projetos': typeof ProjetosRoute
  '/viagens': typeof ViagensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigos'
    | '/corridas'
    | '/eventos'
    | '/livros'
    | '/projetos'
    | '/viagens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigos'
    | '/corridas'
    | '/eventos'
    | '/livros'
    | '/projetos'
    | '/viagens'
  id:
    | '__root__'
    | '/'
    | '/artigos'
    | '/corridas'
    | '/eventos'
    | '/livros'
    | '/projetos'
    | '/viagens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosRoute: typeof ArtigosRoute
  CorridasRoute: typeof CorridasRoute
  EventosRoute: typeof EventosRoute
  LivrosRoute: typeof LivrosRoute
  ProjetosRoute: typeof ProjetosRoute
  ViagensRoute: typeof ViagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livros': {
      id: '/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof LivrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corridas': {
      id: '/corridas'
      path: '/corridas'
      fullPath: '/corridas'
      preLoaderRoute: typeof CorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosRoute: ArtigosRoute,
  CorridasRoute: CorridasRoute,
  EventosRoute: EventosRoute,
  LivrosRoute: LivrosRoute,
  ProjetosRoute: ProjetosRoute,
  ViagensRoute: ViagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
